services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: genacademy-frontend
    ports:
      - "4200:80"
    networks:
      - mlflow-network

  postgres:
    image: postgres:13
    container_name: mlflow-postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mlflow-network

  minio:
    image: minio/minio:latest
    container_name: mlflow-minio
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - mlflow-network

  minio-setup:
    image: minio/mc
    container_name: mlflow-minio-setup
    depends_on:
      - minio
    networks:
      - mlflow-network
    entrypoint: >
      /bin/sh -c "
      until /usr/bin/mc alias set myminio http://${MINIO_ADDRESS} ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD}; do
        echo 'Aguardando MinIO subir...';
        sleep 2;
      done;
      /usr/bin/mc mb myminio/${BUCKET_NAME} --ignore-existing;
      /usr/bin/mc mb myminio/mlflow --ignore-existing;
      /usr/bin/mc version enable myminio/${BUCKET_NAME};
      /usr/bin/mc version enable myminio/mlflow;
      exit 0;
      "

  mlflow:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mlflow-server
    depends_on:
      - postgres
      - minio
      - minio-setup
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - MLFLOW_S3_ENDPOINT_URL=http://${MINIO_ADDRESS}
      - AWS_ACCESS_KEY_ID=${MINIO_ROOT_USER}
      - AWS_SECRET_ACCESS_KEY=${MINIO_ROOT_PASSWORD}
      - MLFLOW_TRACKING_URI=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - BUCKET_NAME=${BUCKET_NAME}
    networks:
      - mlflow-network
  # Servidor de LLM local
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: always
    networks:
      - mlflow-network

  # Setup do modelo de embeddings no Ollama
  ollama-pull:
    image: ollama/ollama:latest
    container_name: ollama-pull
    depends_on:
      - ollama
    environment:
      - OLLAMA_HOST=${OLLAMA_HOST}
    networks:
      - mlflow-network
    entrypoint: >
      /bin/sh -c "
      until ollama list; do
        echo 'Aguardando Ollama subir...';
        sleep 2;
      done;
      ollama pull nomic-embed-text;
      ollama pull llama2;
      exit 0;
      "

  # Dependencia do Milvus
  etcd:
    image: quay.io/coreos/etcd:v3.5.5
    container_name: milvus-etcd
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - etcd_data:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    networks:
      - mlflow-network

  # Banco Vetorial
  milvus-standalone:
    image: milvusdb/milvus:v2.3.1
    container_name: milvus-standalone
    command: ["milvus", "run", "standalone"]
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: ${MINIO_ADDRESS} # Aponta para o seu MinIO existente
      MINIO_ACCESS_KEY_ID: ${MINIO_ROOT_USER}
      MINIO_SECRET_ACCESS_KEY: ${MINIO_ROOT_PASSWORD}
      MINIO_BUCKET_NAME: ${MINIO_BUCKET_NAME}
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - etcd
      - minio
    networks:
      - mlflow-network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: genacademy-api
    depends_on:
      - milvus-standalone
      - ollama
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    environment:
      - OLLAMA_HOST=${OLLAMA_HOST}
      - MILVUS_HOST=${MILVUS_HOST}
      - BUCKET_NAME=${BUCKET_NAME}
    networks:
      - mlflow-network

networks:
  mlflow-network:
    driver: bridge

volumes:
  ollama_data:
  postgres_data:
  minio_data:
  etcd_data:
